<h3>Getting Tweets</h3>
<div id='twitter-timeline'>
    <?php
        echo "in timeline template file";
        // $tweets = $this->getTimeline('demacmedia', 2);
        // var_dump($tweets);
    ?>
    <?php
        //foreach ($this->getTimeline('demacmedia', 2) as $tweet):
    ?>
    <div class='tweet'><?php
        // print_r($tweets);
        //echo $tweet['text'] ?></div>
    <?php
        //end
    ?>
</div>